### ISSUE TITLE
Can not run docker container

### ISSUE THREAD

**Issue by singh-jay** [ankorstore/yokai-showroom#7]
docker build is successful but when running the container I'm getting the help commands

Steps - 
1. git clone git@github.com:ankorstore/yokai-showroom.git
2. cd http-demo
3. docker build -t http-demo . 
4. docker run -t -p 8080:8080 -p 8081:8081 http-demo

Getting this screen - 
![Screenshot from 2024-05-19 18-34-49](https://github.com/ankorstore/yokai-showroom/assets/36124459/ccfe9d2a-a8aa-478e-9f9a-ca4476b024d7)

In other go project same dockerfile is working fine. Not able to debug the code issue.

**Comment by ekkinox** [comment]
You need to specify the subcommnd name, which is `run`: `docker run -t -p 8080:8080 -p 8081:8081 http-demo run`

But I suggest you to run the app via the provided [docker compose](https://github.com/ankorstore/yokai-showroom/blob/main/http-demo/docker-compose.yaml) stack since it'll spin up also the database and jaeger, used by the demo.

You have a [Makefile](https://github.com/ankorstore/yokai-showroom/blob/main/http-demo/Makefile) to ease this, you just need to `make fresh && make logs` to build fresh and stream the logs.

More details in the [readme](https://github.com/ankorstore/yokai-showroom/blob/main/http-demo/README.md#makefile).

**Comment by singh-jay** [comment]
Thanks, It's working.
